// Package oc provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oc

import (
	"encoding/json"
)

// Event defines model for Event.
type Event struct {
	ID         string          `json:"id"`
	Properties json.RawMessage `json:"properties"`
	Type       string          `json:"type"`
}

// PermissionRequest defines model for PermissionRequest.
type PermissionRequest struct {
	ID         string `json:"id"`
	Permission string `json:"permission"`
	SessionID  string `json:"sessionID"`
}

// Session defines model for Session.
type Session struct {
	Agent     string      `json:"agent"`
	Directory string      `json:"directory"`
	ID        string      `json:"id"`
	ParentID  string      `json:"parentID"`
	Slug      string      `json:"slug"`
	Time      SessionTime `json:"time"`
	Title     string      `json:"title"`
}

// SessionTime defines model for SessionTime.
type SessionTime struct {
	Created int64 `json:"created"`
	Updated int64 `json:"updated"`
}

// Status defines model for Status.
type Status struct {
	Message string `json:"message"`
	Type    string `json:"type"`
}
